# Generated by Django 5.1.6 on 2025-03-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_rename_created_at_contact_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='car_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
