# Generated by Django 5.1.6 on 2025-02-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_features_alter_car_interior'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.CharField(choices=[('Acura', 'Acura'), ('Alfa Romeo', 'Alfa Romeo'), ('Aston Martin', 'Aston Martin'), ('Audi', 'Audi'), ('Bentley', 'Bentley'), ('BMW', 'BMW'), ('Bugatti', 'Bugatti'), ('Buick', 'Buick'), ('Cadillac', 'Cadillac'), ('Chevrolet', 'Chevrolet'), ('Chrysler', 'Chrysler'), ('Citroën', 'Citroën'), ('Dacia', 'Dacia'), ('Daihatsu', 'Daihatsu'), ('Dodge', 'Dodge'), ('Ferrari', 'Ferrari'), ('Fiat', 'Fiat'), ('Ford', 'Ford'), ('Genesis', 'Genesis'), ('GMC', 'GMC'), ('Great Wall', 'Great Wall'), ('Haval', 'Haval'), ('Honda', 'Honda'), ('Hyundai', 'Hyundai'), ('Infiniti', 'Infiniti'), ('Isuzu', 'Isuzu'), ('Jaguar', 'Jaguar'), ('Jeep', 'Jeep'), ('Kia', 'Kia'), ('Koenigsegg', 'Koenigsegg'), ('Lamborghini', 'Lamborghini'), ('Lancia', 'Lancia'), ('Land Rover', 'Land Rover'), ('Lexus', 'Lexus'), ('Lincoln', 'Lincoln'), ('Lotus', 'Lotus'), ('Lucid', 'Lucid'), ('Mahindra', 'Mahindra'), ('Maserati', 'Maserati'), ('Maybach', 'Maybach'), ('Mazda', 'Mazda'), ('McLaren', 'McLaren'), ('Mercedes-Benz', 'Mercedes-Benz'), ('MG', 'MG'), ('Mini', 'Mini'), ('Mitsubishi', 'Mitsubishi'), ('Nio', 'Nio'), ('Nissan', 'Nissan'), ('Opel', 'Opel'), ('Pagani', 'Pagani'), ('Peugeot', 'Peugeot'), ('Polestar', 'Polestar'), ('Pontiac', 'Pontiac'), ('Porsche', 'Porsche'), ('Proton', 'Proton'), ('Ram', 'Ram'), ('Ravon', 'Ravon'), ('Renault', 'Renault'), ('Rimac', 'Rimac'), ('Rivian', 'Rivian'), ('Rolls-Royce', 'Rolls-Royce'), ('Saab', 'Saab'), ('Saturn', 'Saturn'), ('Scion', 'Scion'), ('Seat', 'Seat'), ('Skoda', 'Skoda'), ('Smart', 'Smart'), ('SsangYong', 'SsangYong'), ('Subaru', 'Subaru'), ('Suzuki', 'Suzuki'), ('Tata', 'Tata'), ('Tesla', 'Tesla'), ('Toyota', 'Toyota'), ('Vauxhall', 'Vauxhall'), ('Volkswagen', 'Volkswagen'), ('Volvo', 'Volvo'), ('Wuling', 'Wuling'), ('Zotye', 'Zotye'), ('Unknown', 'Unknown')], default='Unknown', max_length=20),
        ),
    ]
